backend:
  name: git-gateway
  branch: master

media_folder: content/assets
public_folder: /

collections:
  - name: "home"
    label: "Homepage"
    file: "site/content/_home.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Intro", name: "intro", widget: "markdown" }
  - name: "about"
    label: "About"
    file: "site/content/_about.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "One Liner", name: "short description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "project"
    label: "Project"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "work"
    label: "Work"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
